#!/bin/sh
export DAFNE_ONLINE_HOME="{{pkg.path}}"
export DAFNE_ONLINE_DATA="{{pkg.svc_data_path}}"

echo "Removing previous version deployed at ${DAFNE_ONLINE_DATA}"
rm -rf ${DAFNE_ONLINE_DATA}/*

echo "Deploying new version from ${DAFNE_ONLINE_HOME} to ${DAFNE_ONLINE_DATA}"
cp -a ${DAFNE_ONLINE_HOME}/dist ${DAFNE_ONLINE_DATA}/dist

echo "Linking database.yml"
ln -sf {{pkg.svc_config_path}}/database.yml ${DAFNE_ONLINE_DATA}/dist/config/database.yml

export GEM_HOME="${DAFNE_ONLINE_DATA}/dist/vendor/bundle/ruby/2.3.0"
export GEM_PATH="$(hab pkg path core/ruby)/lib/ruby/gems/2.3.0:$(hab pkg path core/bundler):$GEM_HOME"
export LD_LIBRARY_PATH="$(hab pkg path core/gcc-libs)/lib"
export PATH="$PATH:${DAFNE_ONLINE_DATA}/dist/bin"
export RAILS_ENV="production"

chown -R hab:hab ${DAFNE_ONLINE_DATA}/dist
cd ${DAFNE_ONLINE_DATA}/dist

exec 2>&1

if [[ ! -f ${DAFNE_ONLINE_DATA}/.migrations_complete ]]; then
  echo "Running 'rake db:create' in ${PWD}"
  bundle exec bin/rake db:create
  echo "Running 'rake db:migrate' in ${PWD}"
  bundle exec  bin/rake db:migrate
  echo "Running 'rake db:seed' in ${PWD}"
  bundle exec bin/rake db:seed && touch $DAFNE_ONLINE_DATA/.migrations_complete
fi
