#!/bin/sh
export DAFNE_ONLINE_DATA="{{pkg.svc_data_path}}"
export GEM_HOME="${DAFNE_ONLINE_DATA}/dist/vendor/bundle/ruby/2.3.0"
export GEM_PATH="$(hab pkg path core/ruby)/lib/ruby/gems/2.3.0:$(hab pkg path core/bundler):$GEM_HOME"
export LD_LIBRARY_PATH="$(hab pkg path core/gcc-libs)/lib"
export PATH="$PATH:${DAFNE_ONLINE_DATA}/dist/bin"
export RAILS_ENV="production"

cd $DAFNE_ONLINE_DATA/dist

exec 2>&1
#exec chpst -u hab unicorn -p {{cfg.rails_port}}
exec unicorn -p {{cfg.rails_port}}
